// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbwedeqfndwqtgfrmewa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZid2VkZXFmbmR3cXRnZnJtZXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MTk4NjEsImV4cCI6MjA2NTE5NTg2MX0.LpBYCW2in1KYNYYj9FhKnw407XsONsCgXZnVn0pxlI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);